name: CI

on:
  push:
  pull_request:

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    # run job backend
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          # cache  lockfile  backend only
          cache-dependency-path: backend/package-lock.json

      #  lockfile (เร็ว/เสถียรสำหรับ CI)
      - name: Install (clean)
        run: npm ci

      # (integration + MBT + RBAC + fuzz)
      - name: Run tests
        run: npm test

      - name: Upload mochawesome report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: backend/mochawesome-report
          if-no-files-found: ignore
